root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/shuangtang-backend"
  cmd = "go build -o ./tmp/shuangtang-backend ./cmd/server"
  delay = 1000
  exclude_dir = ["tmp", "web", "migrations", "locales"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal"]
  include_ext = ["go", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "green"
  runner = "cyan"
  watcher = "magenta"

[log]
  main_only = false
  time = true
