DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS location_shares CASCADE;
DROP TABLE IF EXISTS alarm_closes CASCADE;
DROP TABLE IF EXISTS alarms CASCADE;
DROP TABLE IF EXISTS secret_messages CASCADE;
DROP TABLE IF EXISTS albums CASCADE;
DROP TABLE IF EXISTS wishlist_items CASCADE;
DROP TABLE IF EXISTS check_in_records CASCADE;
DROP TABLE IF EXISTS check_in_tasks CASCADE;
DROP TABLE IF EXISTS anniversaries CASCADE;
DROP TABLE IF EXISTS moments CASCADE;
DROP TABLE IF EXISTS couples CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS system_configs CASCADE;
DROP TABLE IF EXISTS translations CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp";
DROP EXTENSION IF EXISTS "postgis";
